export const members = [
	{ nombre: 'Mariano', 'inversión inicial': 5000 },
	{ nombre: 'Eusebio', 'inversión inicial': 3000 },
	{ nombre: 'Pablo', 'inversión inicial': 5000 },
	{ nombre: 'Lucía', 'inversión inicial': 8000 },
	{ nombre: 'Juliana', 'inversión inicial': 2000 },
	{ nombre: 'Javier', 'inversión inicial': 4000 },
	{ nombre: 'Patricia', 'inversión inicial': 7000 },
	{ nombre: 'Laura', 'inversión inicial': 4000 },
	{ nombre: 'Roberto', 'inversión inicial': 5000 },
	{ nombre: 'Norberto', 'inversión inicial': 3000 },
	{ nombre: 'Beatriz', 'inversión inicial': 5000 },
	{ nombre: 'Gonzalo', 'inversión inicial': 5000 },
	{ nombre: 'Manuel', 'inversión inicial': 5000 },
	{ nombre: 'Montserrat', 'inversión inicial': 6000 },
	{ nombre: 'Raúl', 'inversión inicial': 3000 },
	{ nombre: 'Isabel', 'inversión inicial': 3000 },
	{ nombre: 'Alberto', 'inversión inicial': 6000 },
	{ nombre: 'Alba', 'inversión inicial': 8000 },
	{ nombre: 'Sergio', 'inversión inicial': 4000 },
	{ nombre: 'Carmen', 'inversión inicial': 3000 },
	{ nombre: 'Natalia', 'inversión inicial': 3000 }
];

export const randomNames = [
	'Antonio',
	'Marta',
	'Ricardo',
	'Ana',
	'Víctor',
	'Sonia',
	'Diego',
	'Elena',
	'Juan',
	'Irene',
	'Andrés',
	'Claudia',
	'Fernando',
	'Teresa',
	'David',
	'Silvia',
	'Pedro',
	'Cristina',
	'Joaquín',
	'Lorena'
];
